/*
 * ViewPanel.java
 *
 * Created on August 10, 2008, 12:09 AM
 */

package gui;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.AffineTransform;
import java.awt.image.RenderedImage;

/**
 *
 * @author  Administrator
 */
public class ViewPanel extends javax.swing.JPanel{
    private RenderedImage renderedImage;

    /** Creates new form ViewPanel */
    public ViewPanel(RenderedImage renderedImage) {
        this.renderedImage=renderedImage;
        setPreferredSize(new Dimension(renderedImage.getWidth(),renderedImage.getHeight()));
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paint(Graphics graphics) {
        Graphics2D graphics2D=(Graphics2D)graphics;
        
        Dimension size = getSize();
        graphics2D.drawRenderedImage(renderedImage, new AffineTransform());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
