/*
 * ViewWindow.java
 *
 * Created on August 9, 2008, 11:34 PM
 */
package gui;

import gui.window.ProductInformationWindow;
import java.awt.BorderLayout;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.FileNotFoundException;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import reader.GeoTiffReader;

/**
 *
 * @author  Administrator
 */
public class ViewWindow extends javax.swing.JFrame implements IViewWindow {

    private File file;
    private GeoTiffReader gTiffReader;
    private JScrollPane viewScrollPane;
    private RenderedImage renderedImage;
    private ViewPanel viewPanel;
    private ProductInformationWindow productInformationWindow;
    private String mapName;
    private IViewListener viewListener;

    /** Creates new form ViewWindow */
    public ViewWindow(File file) throws FileNotFoundException, Exception {
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/images/title.png"));
        setIconImage(imageIcon.getImage());
        setTitle(file.getName());
        mapName = file.getName();
        this.file = file;
        gTiffReader = new GeoTiffReader(file);
        renderedImage = gTiffReader.getRenderedImage();
        initComponents();
        setLayout(new BorderLayout());
        viewPanel = new ViewPanel(renderedImage);
        viewScrollPane = new JScrollPane(viewPanel);
        add(viewScrollPane, BorderLayout.CENTER);
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width - 600) / 2, (screenSize.height - 500) / 2, 600, 500);
        productInformationWindow = new ProductInformationWindow(gTiffReader);
    }

    public void addViewListener(IViewListener viewListener) {
        this.viewListener = viewListener;
        viewListener.mapCreated(this);
    }

    public void removeViewListener(IViewListener viewListener) {
        viewListener.mapClosed(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewWindowMenuBar = new javax.swing.JMenuBar();
        windowMenu = new javax.swing.JMenu();
        productInformationMenuItem = new javax.swing.JMenuItem();
        propertiesMenu = new javax.swing.JMenu();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        windowMenu.setMnemonic('H');
        windowMenu.setText("Window");

        productInformationMenuItem.setText("Product Information");
        productInformationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productInformationMenuItemActionPerformed(evt);
            }
        });
        windowMenu.add(productInformationMenuItem);

        viewWindowMenuBar.add(windowMenu);

        propertiesMenu.setText("Properties");
        propertiesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                propertiesMenuMouseClicked(evt);
            }
        });
        propertiesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertiesMenuActionPerformed(evt);
            }
        });
        viewWindowMenuBar.add(propertiesMenu);

        setJMenuBar(viewWindowMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-408)/2, (screenSize.height-334)/2, 408, 334);
    }// </editor-fold>//GEN-END:initComponents

private void productInformationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productInformationMenuItemActionPerformed
    productInformationWindow.setVisible(true);
    productInformationWindow.refreshTagInfoPanel();
}//GEN-LAST:event_productInformationMenuItemActionPerformed

private void propertiesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertiesMenuActionPerformed
}//GEN-LAST:event_propertiesMenuActionPerformed

private void propertiesMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_propertiesMenuMouseClicked
}//GEN-LAST:event_propertiesMenuMouseClicked

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    removeViewListener(viewListener);
}//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem productInformationMenuItem;
    private javax.swing.JMenu propertiesMenu;
    private javax.swing.JMenuBar viewWindowMenuBar;
    private javax.swing.JMenu windowMenu;
    // End of variables declaration//GEN-END:variables

    public String getMapName() {

        return mapName;
    }

}
