/*
 * GeogCitationGeoKeyPanel.java
 *
 * Created on August 17, 2008, 12:05 PM
 */
package geokey.panel;

/**
 *
 * @author  kamleshp
 */
public class GeogCitationGeoKeyPanel extends javax.swing.JPanel {

    /** Creates new form GeogCitationGeoKeyPanel */
    public GeogCitationGeoKeyPanel(String[] geographicType) {
        initComponents();
        String temp = "";
        int index = 0;
        do {
            if (index > 0&&geographicType[index].trim().length()>0) {
                temp += ", ";
            }
            temp += (geographicType[index].trim());
            index++;
        } while (index < geographicType.length);
        geographicalTypeTextField.setText(temp);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        geographicalTypeTextField = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Geographical Citation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 153, 255))); // NOI18N

        jLabel1.setText("Type   :");

        geographicalTypeTextField.setEditable(false);
        geographicalTypeTextField.setText("type");
        geographicalTypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geographicalTypeTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(geographicalTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(geographicalTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void geographicalTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geographicalTypeTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_geographicalTypeTextFieldActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField geographicalTypeTextField;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
