/*
 * GTCitationGeoKeyPanel.java
 *
 * Created on August 17, 2008, 11:00 AM
 */

package geokey.panel;

/**
 *
 * @author  kamleshp
 */
public class GTCitationGeoKeyPanel extends javax.swing.JPanel {

    /** Creates new form GTCitationGeoKeyPanel */
    public GTCitationGeoKeyPanel(String[] companyInformation) {
        initComponents();
        String temp = "";
        int index = 0;
        do {
            if (index > 0&&companyInformation[index].trim().length()>0) {
                temp += ", ";
            }
            temp += (companyInformation[index].trim());
            index++;
        } while (index < companyInformation.length);
        companyInfoTextField.setText(temp);
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        companyInfoLabel = new javax.swing.JLabel();
        companyInfoTextField = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GT Citation Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 102, 255))); // NOI18N

        companyInfoLabel.setText("Information   :");

        companyInfoTextField.setEditable(false);
        companyInfoTextField.setText("information");
        companyInfoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyInfoTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(companyInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(companyInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(companyInfoLabel)
                .addComponent(companyInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void companyInfoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyInfoTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_companyInfoTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel companyInfoLabel;
    private javax.swing.JTextField companyInfoTextField;
    // End of variables declaration//GEN-END:variables

}
