/*
 * GTRasterTypeGeoKeyPanel.java
 *
 * Created on August 17, 2008, 10:50 AM
 */

package geokey.panel;

/**
 *
 * @author  kamleshp
 */
public class GTRasterTypeGeoKeyPanel extends javax.swing.JPanel {

    /** Creates new form GTRasterTypeGeoKeyPanel */
    public GTRasterTypeGeoKeyPanel(String rasterCode) {
        initComponents();
        rasterCodeTextField.setText(rasterCode);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rasterCodeLabel = new javax.swing.JLabel();
        rasterCodeTextField = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Raster Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 102, 255))); // NOI18N

        rasterCodeLabel.setText("Raster  Code   :");

        rasterCodeTextField.setEditable(false);
        rasterCodeTextField.setText("raster code");
        rasterCodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rasterCodeTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(rasterCodeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rasterCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rasterCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(rasterCodeLabel))
        );
    }// </editor-fold>//GEN-END:initComponents

private void rasterCodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rasterCodeTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_rasterCodeTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel rasterCodeLabel;
    private javax.swing.JTextField rasterCodeTextField;
    // End of variables declaration//GEN-END:variables

}
